const TimestampWebpackPlugin = require('timestamp-webpack-plugin');
const path = require('path');
const webpack = require('webpack');

module.exports = {
  context: path.resolve('js'),

  devServer: {
    contentBase: 'public'
  },

  entry: ['./app'],

  output: {
    path: path.resolve('build/js'),
    publicPath: '/public/assets/js',
    filename: 'bundle.js'
  },

  module: {
    loaders: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel'
      }
    ]
  },

  plugins: [
    new webpack.ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery',
      'window.jQuery': 'jquery'
    }),

    new TimestampWebpackPlugin({
      path: __dirname,
      filename: 'timestamp.json'
    }),

    new webpack.BannerPlugin('********************\nGenerated by Webpack\n********************\n')
  ],

  resolve: {
    extensions: ['', '.js'] // default config. add more extensions when needed
  }
};
